services:
  - type: web
    name: whatshouldlnameit
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: whatshouldlnameit-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
