import Header from "@/components/header";
import Footer from "@/components/footer";
import { Card, CardContent } from "@/components/ui/card";

export default function Terms() {
  return (
    <div className="min-h-screen bg-muted">
      <Header />
      
      <main className="pt-16 pb-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-16">
            <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-6">
              Terms of Service
            </h1>
            <p className="text-lg text-muted-foreground">
              Last updated: December 15, 2024
            </p>
          </div>

          <Card>
            <CardContent className="p-8 prose max-w-none">
              <div className="space-y-8">
                <section>
                  <h2 className="text-2xl font-bold text-foreground mb-4">Agreement to Terms</h2>
                  <p className="text-muted-foreground mb-4">
                    By accessing and using WhatShouldINameIt? (the "Service"), you agree to be bound by these 
                    Terms of Service ("Terms"). If you do not agree to these Terms, you may not use our Service.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-foreground mb-4">Description of Service</h2>
                  <p className="text-muted-foreground mb-4">
                    WhatShouldINameIt? provides AI-powered business naming services, including name generation, 
                    domain availability checking, and related tools to help users find suitable names for their 
                    businesses, projects, or ventures.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-foreground mb-4">User Accounts</h2>
                  <ul className="list-disc list-inside text-muted-foreground mb-4 space-y-2">
                    <li>You must provide accurate and complete information when creating an account</li>
                    <li>You are responsible for maintaining the security of your account credentials</li>
                    <li>You must notify us immediately of any unauthorized access to your account</li>
                    <li>One person or entity may not maintain multiple free accounts</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-foreground mb-4">Acceptable Use</h2>
                  <p className="text-muted-foreground mb-4">You agree not to:</p>
                  <ul className="list-disc list-inside text-muted-foreground mb-4 space-y-2">
                    <li>Use the Service for any illegal or unauthorized purpose</li>
                    <li>Generate names for offensive, harmful, or discriminatory content</li>
                    <li>Attempt to reverse engineer or copy our algorithms</li>
                    <li>Use automated systems to access the Service beyond normal usage</li>
                    <li>Interfere with or disrupt the Service or servers</li>
                    <li>Collect user information without consent</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-foreground mb-4">Intellectual Property</h2>
                  <h3 className="text-xl font-semibold text-foreground mb-3">Our Content</h3>
                  <p className="text-muted-foreground mb-4">
                    The Service, including software, algorithms, design, and content, is owned by us and 
                    protected by intellectual property laws. You may not copy, modify, or distribute our content.
                  </p>
                  
                  <h3 className="text-xl font-semibold text-foreground mb-3">Generated Names</h3>
                  <p className="text-muted-foreground mb-4">
                    Names generated by our Service are provided as suggestions only. We do not claim ownership 
                    of generated names, nor do we guarantee their availability or legal status. You are responsible 
                    for conducting proper trademark and legal research before using any suggested name.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-foreground mb-4">Payment and Billing</h2>
                  <ul className="list-disc list-inside text-muted-foreground mb-4 space-y-2">
                    <li>Paid subscriptions are billed in advance on a monthly or annual basis</li>
                    <li>All fees are non-refundable except as required by law or our refund policy</li>
                    <li>We may change pricing with 30 days notice to existing subscribers</li>
                    <li>Failure to pay may result in suspension or termination of your account</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-foreground mb-4">Disclaimers</h2>
                  <p className="text-muted-foreground mb-4">
                    THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, 
                    EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
                  </p>
                  <ul className="list-disc list-inside text-muted-foreground mb-4 space-y-2">
                    <li>We do not guarantee name availability or uniqueness</li>
                    <li>Domain availability information may not be current</li>
                    <li>We are not responsible for trademark conflicts</li>
                    <li>Generated names may not be suitable for all purposes</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-foreground mb-4">Limitation of Liability</h2>
                  <p className="text-muted-foreground mb-4">
                    TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, 
                    SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, ARISING FROM YOUR USE OF THE SERVICE.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-foreground mb-4">Termination</h2>
                  <p className="text-muted-foreground mb-4">
                    We may terminate or suspend your account and access to the Service at our discretion, 
                    with or without notice, for violations of these Terms or other reasons.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-foreground mb-4">Privacy</h2>
                  <p className="text-muted-foreground mb-4">
                    Your privacy is important to us. Please review our Privacy Policy to understand how we 
                    collect, use, and protect your information.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-foreground mb-4">Changes to Terms</h2>
                  <p className="text-muted-foreground mb-4">
                    We reserve the right to modify these Terms at any time. We will notify users of significant 
                    changes via email or through the Service. Continued use after changes constitutes acceptance.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-foreground mb-4">Governing Law</h2>
                  <p className="text-muted-foreground mb-4">
                    These Terms are governed by the laws of California, United States, without regard to 
                    conflict of law principles.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-bold text-foreground mb-4">Contact Information</h2>
                  <p className="text-muted-foreground">
                    For questions about these Terms, contact us at:
                    <br />
                    Email: legal@whatshouldlnameit.com
                    <br />
                    Address: 123 Innovation Drive, San Francisco, CA 94105
                  </p>
                </section>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>

      <Footer />
    </div>
  );
}